os: osx
osx_image: Xcode 9.3beta
language: swift
xcode_sdk: macosx10.12
script:
    - xcodebuild test -project AtlasCore.xcodeproj -scheme AtlasCore-Package -sdk macosx10.12 -destination "platform=OS X,arch=x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
