version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: swift package generate-xcodeproj --xcconfig-overrides settings.xcconfig
      - run: xcodebuild test -project AtlasCore.xcodeproj/ -scheme AtlasCore-Package -destination 'platform=OS X,arch=x86_64'
