version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: swift package generate-xcodeproj --xcconfig-overrides settings.xcconfig
      - run: swift test -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.13"
